export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const GAME_ROUTE = '/game'
export const NOT_FOUND_PAGE = '/404'
export const CATALOG_SEARCH = '/catalog/search/'